// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0-alpha

package handler

import (
	"net/http"

	data "AgentEarth-Mgr/admin/internal/handler/data"
	"AgentEarth-Mgr/admin/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/batch/close/services",
				Handler: data.BatchCloseServicesHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/create/chain-and-node",
				Handler: data.CreateChainAndNodeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/create/config",
				Handler: data.CreateConfigHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/create/service",
				Handler: data.CreateServiceHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/create/service-and-config",
				Handler: data.CreateServiceAndConfigHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/create/services",
				Handler: data.CreateServicesHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/update/service/desc",
				Handler: data.UpdateServiceDescHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/admin/data"),
	)
}
