// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	source "AgentEarth-Mgr/admin/internal/handler/source"
	"AgentEarth-Mgr/admin/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/account/list",
				Handler: source.AccountListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/account/sync",
				Handler: source.AccountSyncHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/account/sync-test-to-prod",
				Handler: source.AccountSyncTestToProdHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/detail/:id",
				Handler: source.DetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: source.ListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/service/batch/create",
				Handler: source.ServiceBatchCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/service/offline",
				Handler: source.ServiceOfflineHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/service/sync-test-to-prod",
				Handler: source.ServiceSyncTestToProdHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/service/test-status-update",
				Handler: source.ServiceTestStatusUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/update",
				Handler: source.UpdateHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/admin/source"),
	)
}
