// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0-alpha

package handler

import (
	"net/http"

	data "AgentEarth-Mgr/admin/internal/handler/data"
	mcp "AgentEarth-Mgr/admin/internal/handler/mcp"
	source "AgentEarth-Mgr/admin/internal/handler/source"
	"AgentEarth-Mgr/admin/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/batch/close/services",
				Handler: data.BatchCloseServicesHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/create/chain-and-node",
				Handler: data.CreateChainAndNodeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/create/config",
				Handler: data.CreateConfigHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/create/service",
				Handler: data.CreateServiceHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/create/service-and-config",
				Handler: data.CreateServiceAndConfigHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/create/services",
				Handler: data.CreateServicesHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/update/service/desc",
				Handler: data.UpdateServiceDescHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/admin/data"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/service/batch-close",
				Handler: mcp.ServiceBatchCloseHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/service/config/account/delete",
				Handler: mcp.ServiceConfigAccountDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/service/config/account/list",
				Handler: mcp.ServiceConfigAccountListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/service/config/account/update-status",
				Handler: mcp.ServiceConfigAccountUpdateStatusHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/service/delete",
				Handler: mcp.ServiceDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/service/detail/:id",
				Handler: mcp.ServiceDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/service/install/list",
				Handler: mcp.ServiceInstallListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/service/list",
				Handler: mcp.ServiceListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/service/pre_install/create",
				Handler: mcp.ServicePreInstallCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/service/shell/create",
				Handler: mcp.ServiceShellCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/service/task/create",
				Handler: mcp.ServiceTaskCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/service/update/created-group",
				Handler: mcp.ServiceUpdateCreatedGroupHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/service/update/is_create",
				Handler: mcp.ServiceUpdateIsCreateHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/admin/mcp"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/account/list",
				Handler: source.AccountListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/account/sync",
				Handler: source.AccountSyncHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/account/sync-test-to-prod",
				Handler: source.AccountSyncTestToProdHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/detail/:id",
				Handler: source.DetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: source.ListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/service/batch/create",
				Handler: source.ServiceBatchCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/service/offline",
				Handler: source.ServiceOfflineHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/service/sync-test-to-prod",
				Handler: source.ServiceSyncTestToProdHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/service/test-status-update",
				Handler: source.ServiceTestStatusUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/update",
				Handler: source.UpdateHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/admin/source"),
	)
}
