// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0-alpha

package types

type BaseListReq struct {
	Page   int64  `form:"page, optional"`
	Size   int64  `form:"size, optional"`
	Search string `form:"search, optional"`
}

type BaseResp struct {
	Code    int64                  `json:"code"`
	Message string                 `json:"message"`
	Data    map[string]interface{} `json:"data"`
}

type BatchCloseServicesReq struct {
	TestStatus int64 `json:"test_status"`
}

type CreateChainAndNodeReq struct {
	Ids []int64 `json:"ids,optional"`
}

type CreateConfigReq struct {
	TestStatus int64 `json:"test_status"`
}

type CreateServiceAndConfigReq struct {
	TestStatus int64 `json:"test_status"`
}

type UpdateServiceDescReq struct {
	ServiceID string `json:"service_id,optional"`
}
