// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AccountListReq struct {
	BaseListReq
	SourceId int64 `form:"source_id,optional"`
}

type AccountSyncReq struct {
	Ids []int64 `json:"ids"` // 账号ID列表
}

type BaseListReq struct {
	Page   int64  `form:"page,optional"`
	Size   int64  `form:"size,optional"`
	Search string `form:"search,optional"`
	Sort   string `form:"sort,optional"`
	Order  string `form:"order,optional"`
}

type BaseResp struct {
	Code    int64                  `json:"code"`
	Message string                 `json:"message"`
	Data    map[string]interface{} `json:"data"`
}

type BatchCloseServicesReq struct {
	TestStatus int64 `json:"test_status"`
}

type CreateChainAndNodeReq struct {
	Ids []int64 `json:"ids,omitempty"`
}

type CreateConfigReq struct {
	TestStatus int64 `json:"test_status"`
}

type CreateServiceAndConfigReq struct {
	TestStatus int64 `json:"test_status"`
}

type CreateServiceConfigManualReq struct {
	Name            string `json:"name"`
	Type            string `json:"type"`
	Description     string `json:"description"`
	ProjectName     string `json:"project_name"`
	MaxInstance     int64  `json:"max_instance"`
	LaunchInfo      string `json:"launch_info"`
	ConnectInfo     string `json:"connect_info"`
	InstallInfo     string `json:"install_info"`
	AccountRequired int64  `json:"account_required"`
	TestStatus      int64  `json:"test_status"`
	OnlineStatus    int64  `json:"online_status"`
}

type DetailReq struct {
	Id int64 `path:"id"`
}

type GetServiceConfigListReq struct {
	BaseListReq
	FilterName            string `form:"filter_name,optional"`
	FilterType            string `form:"filter_type,optional"`
	FilterAccountRequired string `form:"filter_account_required,optional"`
	FilterTestStatus      string `form:"filter_test_status,optional"`
	FilterOnlineStatus    string `form:"filter_online_status,optional"`
	SortField             string `form:"sort_field,optional"`
	SortOrder             string `form:"sort_order,optional"`
}

type GetServiceConfigListResp struct {
	List  []ServiceConfigItem `json:"list"`
	Total int64               `json:"total"`
}

type IdsReq struct {
	Ids []int64 `json:"ids"`
}

type LoginData struct {
	Token    string `json:"token"`
	UserId   string `json:"user_id"`
	Username string `json:"username"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Code    int64     `json:"code"`
	Message string    `json:"message"`
	Data    LoginData `json:"data"`
}

type ServiceBatchCloseReq struct {
	Ids []int64 `json:"ids"`
}

type ServiceBatchCreateReq struct {
	Ids []int64 `json:"ids"` // 数据源ID列表
}

type ServiceBatchUpdatePriceReq struct {
	Ids       []int64 `json:"ids,omitempty"`
	Price     int64   `json:"price"`
	IsAll     bool    `json:"is_all,omitempty"`
	Search    string  `json:"search,omitempty"`
	Enabled   int     `json:"enabled,omitempty"`
	IsInstall int     `json:"is_install,omitempty"`
	IsCreated int     `json:"is_created,omitempty"`
	ServerId  string  `json:"server_id,omitempty"`
}

type ServiceConfigAccountCreateReq struct {
	Name     string `json:"name"`
	AuthInfo string `json:"auth_info"`
	ConfigId int64  `json:"config_id"`
	Status   string `json:"status"`
}

type ServiceConfigAccountDeleteReq struct {
	Ids []int64 `json:"ids"`
}

type ServiceConfigAccountListReq struct {
	BaseListReq
	ServerId string `form:"server_id,optional"`
	Status   string `form:"status,optional"`
	ConfigId int64  `form:"config_id,optional"`
}

type ServiceConfigAccountUpdateReq struct {
	Id       int64   `json:"id"`
	Name     string  `json:"name"`
	AuthInfo *string `json:"auth_info,omitempty"`
	ConfigId *int64  `json:"config_id,omitempty"`
	Status   string  `json:"status"`
}

type ServiceConfigAccountUpdateStatusReq struct {
	Ids    []int64 `json:"ids"`
	Status string  `json:"status"`
}

type ServiceConfigDeleteReq struct {
	Ids []int64 `json:"ids"`
}

type ServiceConfigItem struct {
	Id                int64  `json:"id"`
	Name              string `json:"name"`
	Type              string `json:"type"`
	Description       string `json:"description"`
	ProjectName       string `json:"project_name"`
	MaxInstance       int64  `json:"max_instance"`
	LaunchInfo        string `json:"launch_info"`
	ConnectInfo       string `json:"connect_info"`
	InstallInfo       string `json:"install_info"`
	AccountRequired   int64  `json:"account_required"`
	TestStatus        int64  `json:"test_status"`
	OnlineStatus      int64  `json:"online_status"`
	ExternalServiceId string `json:"external_service_id"`
	ServerId          string `json:"server_id"`
	CreateStatus      bool   `json:"create_status"`
	CreateTime        string `json:"create_time"`
	UpdateTime        string `json:"update_time"`
}

type ServiceDeleteReq struct {
	Ids []int64 `json:"ids"`
}

type ServiceInstallListReq struct {
	BaseListReq
	ServerId string `form:"server_id,optional"`
}

type ServiceListReq struct {
	BaseListReq
	Enabled   int64  `form:"enabled,optional"`
	IsInstall int64  `form:"is_install,optional"`
	IsCreated int64  `form:"is_created,optional"`
	ServerId  string `form:"server_id,optional"`
}

type ServiceOfflineReq struct {
	Ids []int64 `json:"ids"` // 数据源ID列表
}

type ServicePreInstallCreateReq struct {
	InstallIds []int64 `json:"install_ids"`
}

type ServiceShellCreateReq struct {
	InstallIds []int64 `json:"install_ids"`
}

type ServiceTaskCreateReq struct {
	Ids []int64 `json:"ids"`
}

type ServiceTestStatusUpdateReq struct {
	Ids        []int64 `json:"ids"`         // 数据源ID
	TestStatus int64   `json:"test_status"` // 测试状态
}

type ServiceUpdateCreatedGroupReq struct {
	Ids          []int64 `json:"ids"`
	CreatedGroup int64   `json:"created_group"`
}

type ServiceUpdateIsCreateReq struct {
	Id        int64 `json:"id"`
	IsCreated bool  `json:"is_created"`
}

type ServiceUpdatePriceReq struct {
	ServerId string `json:"server_id"`
	Price    int64  `json:"price"`
}

type SourceListReq struct {
	BaseListReq
	TestStatus string `form:"test_status,optional"`
	ServerType string `form:"server_type,optional"`
}

type SourceUpdateReq struct {
	Id              int64  `json:"id"`              // 自增ID
	ServerName      string `json:"server_name"`     // 服务名称
	ServerType      string `json:"server_type"`     // 服务类型：stdio,sse,httpStream
	LaunchInfo      string `json:"launch_info"`     // 启动信息，例如：{      "command": "npx",      "args": ["-y", "time-mcp"]}
	ConnectInfo     string `json:"connect_info"`    // 连接信息，如：{  "url": "http://api.remote.com/mcp/sse"}
	Description     string `json:"description"`     // 服务描述
	CodeSourceUrl   string `json:"code_source_url"` // 来源地址：可以是github项目地址，也可以是原MCP服务的文档地址
	TestStatus      int64  `json:"test_status"`     // 测试状态：0 未测试 1 通过 -1 未通过
	DockerCmd       string `json:"docker_cmd"`
	ProjectName     string `json:"project_name"`
	Valuable        string `json:"valuable"`         // 有价值的服务
	Calls           int64  `json:"calls"`            // 流量
	Category        string `json:"category"`         // 品类
	Image           string `json:"image"`            // 图片
	CloneRepository string `json:"clone_repository"` // 克隆仓库地址
	NeedKey         int64  `json:"need_key"`         // 1 需要key 0不需要key
	Install         string `json:"install"`          // 安装命令
}

type UpdateServiceConfigReq struct {
	Id              int64   `json:"id"`
	Name            string  `json:"name"`
	Type            string  `json:"type"`
	Description     string  `json:"description"`
	ProjectName     string  `json:"project_name"`
	MaxInstance     int64   `json:"max_instance"`
	LaunchInfo      *string `json:"launch_info,omitempty"`
	ConnectInfo     *string `json:"connect_info,omitempty"`
	InstallInfo     *string `json:"install_info,omitempty"`
	AccountRequired *int64  `json:"account_required,omitempty"`
	TestStatus      *int64  `json:"test_status,omitempty"`
	OnlineStatus    *int64  `json:"online_status,omitempty"`
}

type UpdateServiceDescReq struct {
	ServiceID string `json:"service_id,omitempty"`
}

type UpdateServiceOnlineReq struct {
	Id           int64 `json:"id"`
	OnlineStatus int64 `json:"online_status"`
}

type UserFundStatsResp struct {
	TotalUsers       int64   `json:"total_users"`
	DailyActiveUsers int64   `json:"daily_active_users"`
	TotalRecharge24h float64 `json:"total_recharge_24h"`
}

type UserItem struct {
	Id               int64   `json:"id"`
	UserStrId        string  `json:"user_str_id"`
	Username         string  `json:"username"`
	Phone            string  `json:"phone"`
	Email            string  `json:"email"`
	AvatarUrl        string  `json:"avatar_url"`
	Status           string  `json:"status"`
	LastLoginAt      string  `json:"last_login_at"`
	CreateTime       string  `json:"create_time"`
	Balance          float64 `json:"balance"`
	DailyConsumption float64 `json:"daily_consumption"` // 日均消费
}

type UserListReq struct {
	Page     int    `form:"page,default=1"`
	PageSize int    `form:"pageSize,default=10"`
	Search   string `form:"search,optional"`
}

type UserListResp struct {
	List  []UserItem `json:"list"`
	Total int64      `json:"total"`
}

type UserDetailReq struct {
	UserStrId string `path:"user_str_id"`
}

type UserDetailResp struct {
	User             UserItem `json:"user"`
	CurrentBalance   float64  `json:"current_balance"`
	DailyConsumption float64  `json:"daily_consumption"`
	FundRunway       int64    `json:"fund_runway"` // 资金续航天数
}

type ConsumptionRecordReq struct {
	UserStrId string `path:"user_str_id"`
	Days      int    `form:"days,default=7"` // 7 或 30
}

type ConsumptionRecordItem struct {
	Day          string  `json:"day"`           // 日期 YYYY-MM-DD
	SelfConsume  float64 `json:"self_consume"`  // 自行消费金额
	SystemDeduct float64 `json:"system_deduct"` // 系统扣减金额（来自充值表负值）
}

type ConsumptionRecordResp struct {
	List []ConsumptionRecordItem `json:"list"`
}

type ManualRechargeReq struct {
	UserStrId  string  `json:"user_str_id"`
	Amount     float64 `json:"amount"`
	ChargeType int64   `json:"charge_type"` // 充值类型：1常规 2系统故障补偿 3活动赠送
	Remarks    string  `json:"remarks,optional"`
}

type ManualRechargeResp struct {
	Success    bool    `json:"success"`
	Message    string  `json:"message"`
	NewBalance float64 `json:"new_balance"`
}

type ManualDeductionReq struct {
	UserStrId  string  `json:"user_str_id"`
	Amount     float64 `json:"amount"`
	ChargeType int64   `json:"charge_type"` // 充值类型：1常规 2系统故障补偿 3活动赠送
	Remarks    string  `json:"remarks,optional"`
}

type ManualDeductionResp struct {
	Success    bool    `json:"success"`
	Message    string  `json:"message"`
	NewBalance float64 `json:"new_balance"`
}

type BalanceHistoryReq struct {
	UserStrId string `path:"user_str_id"`
	Days      int    `form:"days,default=7"` // 7 或 30
}

type BalanceHistoryItem struct {
	Day     string  `json:"day"`     // 日期 YYYY-MM-DD
	Balance float64 `json:"balance"` // 余额
}

type BalanceHistoryResp struct {
	List []BalanceHistoryItem `json:"list"`
}

type FundChangeRecordReq struct {
	UserStrId  string `path:"user_str_id"`
	Filter     string `form:"filter,optional"`      // all, recharge, deduction
	ChargeType int64  `form:"charge_type,optional"` // 1常规 2系统故障补偿 3活动赠送
}

type FundChangeRecordItem struct {
	TransactionTime string  `json:"transaction_time"` // 交易时间
	TypeDescription string  `json:"type_description"` // 类型说明
	ChangeAmount    float64 `json:"change_amount"`    // 变动金额（正数为充值，负数为扣减）
	Status          string  `json:"status"`           // 状态
	Remarks         string  `json:"remarks"`          // 备注/原因
	ChargeType      int64   `json:"charge_type"`      // 充值类型
	ChargeTypeDesc  string  `json:"charge_type_desc"` // 充值类型说明
	Operator        string  `json:"operator"`         // 操作人
}

type FundChangeRecordResp struct {
	List []FundChangeRecordItem `json:"list"`
}
