// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package users

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	aeMcpExternalServicesUserFieldNames          = builder.RawFieldNames(&AeMcpExternalServicesUser{}, true)
	aeMcpExternalServicesUserRows                = strings.Join(aeMcpExternalServicesUserFieldNames, ",")
	aeMcpExternalServicesUserRowsExpectAutoSet   = strings.Join(stringx.Remove(aeMcpExternalServicesUserFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	aeMcpExternalServicesUserRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(aeMcpExternalServicesUserFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	aeMcpExternalServicesUserModel interface {
		Insert(ctx context.Context, data *AeMcpExternalServicesUser) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AeMcpExternalServicesUser, error)
		Update(ctx context.Context, data *AeMcpExternalServicesUser) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAeMcpExternalServicesUserModel struct {
		conn  sqlx.SqlConn
		table string
	}

	AeMcpExternalServicesUser struct {
		Id           int64     `db:"id"`            // 自增ID
		UserId       string    `db:"user_id"`       // 唯一标识
		Username     string    `db:"username"`      // 用户名
		PasswordHash string    `db:"password_hash"` // 用户密码
		Status       string    `db:"status"`        // 账号状态：active-正常, inactive-未激活
		LastLoginAt  time.Time `db:"last_login_at"` // 最后登录时间
		CreateTime   time.Time `db:"create_time"`   // 创建时间
		UpdateTime   time.Time `db:"update_time"`   // 更新时间
	}
)

func newAeMcpExternalServicesUserModel(conn sqlx.SqlConn) *defaultAeMcpExternalServicesUserModel {
	return &defaultAeMcpExternalServicesUserModel{
		conn:  conn,
		table: `"public"."ae_mcp_external_services_user"`,
	}
}

func (m *defaultAeMcpExternalServicesUserModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultAeMcpExternalServicesUserModel) FindOne(ctx context.Context, id int64) (*AeMcpExternalServicesUser, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", aeMcpExternalServicesUserRows, m.table)
	var resp AeMcpExternalServicesUser
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAeMcpExternalServicesUserModel) Insert(ctx context.Context, data *AeMcpExternalServicesUser) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6)", m.table, aeMcpExternalServicesUserRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.UserId, data.Username, data.PasswordHash, data.Status, data.LastLoginAt)
	return ret, err
}

func (m *defaultAeMcpExternalServicesUserModel) Update(ctx context.Context, data *AeMcpExternalServicesUser) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, aeMcpExternalServicesUserRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.UserId, data.Username, data.PasswordHash, data.Status, data.LastLoginAt)
	return err
}

func (m *defaultAeMcpExternalServicesUserModel) tableName() string {
	return m.table
}
