// Code generated by goctl. DO NOT EDIT.

package users

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	aeUserRechargeRecordFieldNames          = builder.RawFieldNames(&AeUserRechargeRecord{}, true)
	aeUserRechargeRecordRows                = strings.Join(aeUserRechargeRecordFieldNames, ",")
	aeUserRechargeRecordRowsExpectAutoSet   = strings.Join(stringx.Remove(aeUserRechargeRecordFieldNames, "id", "create_time", "update_time"), ",")
	aeUserRechargeRecordRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(aeUserRechargeRecordFieldNames, "id", "create_time", "update_time"))
)

type (
	aeUserRechargeRecordModel interface {
		Insert(ctx context.Context, data *AeUserRechargeRecord) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AeUserRechargeRecord, error)
		Update(ctx context.Context, data *AeUserRechargeRecord) error
		Delete(ctx context.Context, id int64) error
		Sum24hRecharge(ctx context.Context) (float64, error)
		GetBalance(ctx context.Context, userId string) (float64, error)
	}

	defaultAeUserRechargeRecordModel struct {
		conn  sqlx.SqlConn
		table string
	}

	AeUserRechargeRecord struct {
		Id             int64     `db:"id"`
		UserId         string    `db:"user_id"`
		XlcreditAmount int64     `db:"xlcredit_amount"`
		PayTime        time.Time `db:"pay_time"`
		CreateTime     time.Time `db:"create_time"`
		UpdateTime     time.Time `db:"update_time"`
		ChargeSource   int64     `db:"charge_source"`
	}
)

func newAeUserRechargeRecordModel(conn sqlx.SqlConn) *defaultAeUserRechargeRecordModel {
	return &defaultAeUserRechargeRecordModel{
		conn:  conn,
		table: `"public"."ae_user_recharge_record"`,
	}
}

func (m *defaultAeUserRechargeRecordModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultAeUserRechargeRecordModel) FindOne(ctx context.Context, id int64) (*AeUserRechargeRecord, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", aeUserRechargeRecordRows, m.table)
	var resp AeUserRechargeRecord
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAeUserRechargeRecordModel) Insert(ctx context.Context, data *AeUserRechargeRecord) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (%s)", m.table, aeUserRechargeRecordRowsExpectAutoSet, aeUserRechargeRecordRowsWithPlaceHolder)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.XlcreditAmount, data.PayTime, data.ChargeSource)
	return ret, err
}

func (m *defaultAeUserRechargeRecordModel) Update(ctx context.Context, data *AeUserRechargeRecord) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, "user_id=$2, xlcredit_amount=$3, pay_time=$4, charge_source=$5")
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.UserId, data.XlcreditAmount, data.PayTime, data.ChargeSource)
	return err
}

func (m *defaultAeUserRechargeRecordModel) Sum24hRecharge(ctx context.Context) (int64, error) {
	// 统计24小时内所有用户充值的总和
	// 使用 pay_time 字段，只统计正值（充值），排除负值（扣减）
	// xlcredit_amount > 0 表示充值，< 0 表示扣减
	now := time.Now()
	startTime := now.Add(-24 * time.Hour)

	// Postgres uses COALESCE to handle null sum
	query := fmt.Sprintf("select COALESCE(sum(xlcredit_amount), 0) from %s where pay_time >= $1 and xlcredit_amount > 0", m.table)
	var total int64
	err := m.conn.QueryRowCtx(ctx, &total, query, startTime)
	return total, err
}

func (m *defaultAeUserRechargeRecordModel) GetBalance(ctx context.Context, userId string) (int64, error) {
	query := fmt.Sprintf("select COALESCE(sum(xlcredit_amount), 0) from %s where user_id = $1", m.table)
	var total int64
	err := m.conn.QueryRowCtx(ctx, &total, query, userId)
	return total, err
}
