// Code generated by goctl. DO NOT EDIT.

package users

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	mcpUserFieldNames          = builder.RawFieldNames(&McpUser{}, true)
	mcpUserRows                = strings.Join(mcpUserFieldNames, ",")
	mcpUserRowsExpectAutoSet   = strings.Join(stringx.Remove(mcpUserFieldNames, "id", "create_time", "update_time"), ",")
	mcpUserRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(mcpUserFieldNames, "id", "create_time", "update_time"))
)

type (
	mcpUserModel interface {
		Insert(ctx context.Context, data *McpUser) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*McpUser, error)
		FindOneByUserId(ctx context.Context, userStrId string) (*McpUser, error)
		Update(ctx context.Context, data *McpUser) error
		Delete(ctx context.Context, id int64) error
		FindList(ctx context.Context, page, pageSize int, search, status string) ([]*McpUser, int64, error)
		CountTodayActive(ctx context.Context) (int64, error)
		CountTotal(ctx context.Context) (int64, error)
	}

	defaultMcpUserModel struct {
		conn  sqlx.SqlConn
		table string
	}

	McpUser struct {
		Id            int64     `db:"id"`
		UserId        string    `db:"user_id"`
		Username      string    `db:"username"`
		PasswordHash  string    `db:"password_hash"`
		Phone         string    `db:"phone"`
		Email         string    `db:"email"`
		AvatarUrl     string    `db:"avatar_url"`
		Status        string    `db:"status"`
		LastLoginAt   time.Time `db:"last_login_at"`
		CreateTime    time.Time `db:"create_time"`
		UpdateTime    time.Time `db:"update_time"`
		OauthId       string    `db:"oauth_id"`
		OauthProvider string    `db:"oauth_provider"`
	}
)

func newMcpUserModel(conn sqlx.SqlConn) *defaultMcpUserModel {
	return &defaultMcpUserModel{
		conn:  conn,
		table: `"public"."ae_user"`,
	}
}

func (m *defaultMcpUserModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultMcpUserModel) FindOne(ctx context.Context, id int64) (*McpUser, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", mcpUserRows, m.table)
	var resp McpUser
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMcpUserModel) FindOneByUserId(ctx context.Context, userStrId string) (*McpUser, error) {
	query := fmt.Sprintf("select %s from %s where user_id = $1 limit 1", mcpUserRows, m.table)
	var resp McpUser
	err := m.conn.QueryRowCtx(ctx, &resp, query, userStrId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMcpUserModel) Insert(ctx context.Context, data *McpUser) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (%s)", m.table, mcpUserRowsExpectAutoSet, mcpUserRowsWithPlaceHolder)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.Username, data.PasswordHash, data.Phone, data.Email, data.AvatarUrl, data.Status, data.LastLoginAt, data.OauthId, data.OauthProvider)
	return ret, err
}

func (m *defaultMcpUserModel) Update(ctx context.Context, data *McpUser) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, "user_id=$2, username=$3, password_hash=$4, phone=$5, email=$6, avatar_url=$7, status=$8, last_login_at=$9, oauth_id=$10, oauth_provider=$11") // Simplified update for brevity, usually auto-generated
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.UserId, data.Username, data.PasswordHash, data.Phone, data.Email, data.AvatarUrl, data.Status, data.LastLoginAt, data.OauthId, data.OauthProvider)
	return err
}

func (m *defaultMcpUserModel) FindList(ctx context.Context, page, pageSize int, search, status string) ([]*McpUser, int64, error) {
	offset := (page - 1) * pageSize
	var resp []*McpUser
	var query string
	var args []interface{}

	where := "1=1"
	if len(search) > 0 {
		where += " AND (username ILIKE $1 OR phone ILIKE $1 OR email ILIKE $1 OR user_id ILIKE $1)"
		args = append(args, "%"+search+"%")
	}

	// 状态筛选：active = 30天内登录, inactive = 超过30天未登录或从未登录
	if status == "active" {
		where += " AND last_login_at >= CURRENT_DATE - INTERVAL '30 days'"
	} else if status == "inactive" {
		where += " AND (last_login_at < CURRENT_DATE - INTERVAL '30 days' OR last_login_at IS NULL)"
	}

	// Count
	var count int64
	countQuery := fmt.Sprintf("select count(*) from %s where %s", m.table, where)
	err := m.conn.QueryRowCtx(ctx, &count, countQuery, args...)
	if err != nil {
		return nil, 0, err
	}

	// List
	query = fmt.Sprintf("select %s from %s where %s order by last_login_at desc nulls last limit $%d offset $%d", mcpUserRows, m.table, where, len(args)+1, len(args)+2)
	args = append(args, pageSize, offset)

	err = m.conn.QueryRowsCtx(ctx, &resp, query, args...)
	return resp, count, err
}

func (m *defaultMcpUserModel) CountTodayActive(ctx context.Context) (int64, error) {
	// today start
	now := time.Now()
	todayStart := time.Date(now.Year(), now.Month(), now.Day(), 0, 0, 0, 0, now.Location())

	query := fmt.Sprintf("select count(*) from %s where last_login_at >= $1", m.table)
	var count int64
	err := m.conn.QueryRowCtx(ctx, &count, query, todayStart)
	return count, err
}

func (m *defaultMcpUserModel) CountTotal(ctx context.Context) (int64, error) {
	query := fmt.Sprintf("select count(*) from %s", m.table)
	var count int64
	err := m.conn.QueryRowCtx(ctx, &count, query)
	return count, err
}
