// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0-alpha

package mcp

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	aeMcpServicesInstallFieldNames          = builder.RawFieldNames(&AeMcpServicesInstall{}, true)
	aeMcpServicesInstallRows                = strings.Join(aeMcpServicesInstallFieldNames, ",")
	aeMcpServicesInstallRowsExpectAutoSet   = strings.Join(stringx.Remove(aeMcpServicesInstallFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	aeMcpServicesInstallRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(aeMcpServicesInstallFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	aeMcpServicesInstallModel interface {
		Insert(ctx context.Context, data *AeMcpServicesInstall) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AeMcpServicesInstall, error)
		Update(ctx context.Context, data *AeMcpServicesInstall) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAeMcpServicesInstallModel struct {
		conn  sqlx.SqlConn
		table string
	}

	AeMcpServicesInstall struct {
		Id            int64     `db:"id"`             // 自增主键
		ServerId      string    `db:"server_id"`      // 服务ID
		InstallCmd    string    `db:"install_cmd"`    // 安装命令
		CreateTime    time.Time `db:"create_time"`    // 创建时间
		UpdateTime    time.Time `db:"update_time"`    // 更新时间
		Port          int64     `db:"port"`           // 使用端口
		Repository    string    `db:"repository"`     // 仓库地址
		PreinstallCmd string    `db:"preinstall_cmd"` // 预装命令
	}
)

func newAeMcpServicesInstallModel(conn sqlx.SqlConn) *defaultAeMcpServicesInstallModel {
	return &defaultAeMcpServicesInstallModel{
		conn:  conn,
		table: `"public"."ae_mcp_services_install"`,
	}
}

func (m *defaultAeMcpServicesInstallModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultAeMcpServicesInstallModel) FindOne(ctx context.Context, id int64) (*AeMcpServicesInstall, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", aeMcpServicesInstallRows, m.table)
	var resp AeMcpServicesInstall
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAeMcpServicesInstallModel) Insert(ctx context.Context, data *AeMcpServicesInstall) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5)", m.table, aeMcpServicesInstallRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ServerId, data.InstallCmd, data.Port, data.Repository, data.PreinstallCmd)
	return ret, err
}

func (m *defaultAeMcpServicesInstallModel) Update(ctx context.Context, data *AeMcpServicesInstall) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, aeMcpServicesInstallRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.ServerId, data.InstallCmd, data.Port, data.Repository, data.PreinstallCmd)
	return err
}

func (m *defaultAeMcpServicesInstallModel) tableName() string {
	return m.table
}
