// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package rules

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	aeRuleExecutionLogFieldNames          = builder.RawFieldNames(&AeRuleExecutionLog{}, true)
	aeRuleExecutionLogRows                = strings.Join(aeRuleExecutionLogFieldNames, ",")
	aeRuleExecutionLogRowsExpectAutoSet   = strings.Join(stringx.Remove(aeRuleExecutionLogFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	aeRuleExecutionLogRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(aeRuleExecutionLogFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	aeRuleExecutionLogModel interface {
		Insert(ctx context.Context, data *AeRuleExecutionLog) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AeRuleExecutionLog, error)
		FindOneByIdempotentKey(ctx context.Context, idempotentKey string) (*AeRuleExecutionLog, error)
		Update(ctx context.Context, data *AeRuleExecutionLog) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAeRuleExecutionLogModel struct {
		conn  sqlx.SqlConn
		table string
	}

	AeRuleExecutionLog struct {
		Id            int64          `db:"id"`
		RuleId        int64          `db:"rule_id"`
		UserId        string         `db:"user_id"`
		ActionType    string         `db:"action_type"`
		ChangeAmount  float64        `db:"change_amount"`
		Status        string         `db:"status"`
		Remark        sql.NullString `db:"remark"`
		ExecSource    string         `db:"exec_source"`
		Operator      string         `db:"operator"`
		IdempotentKey string         `db:"idempotent_key"`
		CreatedTime   time.Time      `db:"created_time"`
		UpdateTime    time.Time      `db:"update_time"`
	}
)

func newAeRuleExecutionLogModel(conn sqlx.SqlConn) *defaultAeRuleExecutionLogModel {
	return &defaultAeRuleExecutionLogModel{
		conn:  conn,
		table: `"public"."ae_rule_execution_log"`,
	}
}

func (m *defaultAeRuleExecutionLogModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultAeRuleExecutionLogModel) FindOne(ctx context.Context, id int64) (*AeRuleExecutionLog, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", aeRuleExecutionLogRows, m.table)
	var resp AeRuleExecutionLog
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAeRuleExecutionLogModel) FindOneByIdempotentKey(ctx context.Context, idempotentKey string) (*AeRuleExecutionLog, error) {
	var resp AeRuleExecutionLog
	query := fmt.Sprintf("select %s from %s where idempotent_key = $1 limit 1", aeRuleExecutionLogRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, idempotentKey)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAeRuleExecutionLogModel) Insert(ctx context.Context, data *AeRuleExecutionLog) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)", m.table, aeRuleExecutionLogRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.RuleId, data.UserId, data.ActionType, data.ChangeAmount, data.Status, data.Remark, data.ExecSource, data.Operator, data.IdempotentKey, data.CreatedTime)
	return ret, err
}

func (m *defaultAeRuleExecutionLogModel) Update(ctx context.Context, newData *AeRuleExecutionLog) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, aeRuleExecutionLogRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Id, newData.RuleId, newData.UserId, newData.ActionType, newData.ChangeAmount, newData.Status, newData.Remark, newData.ExecSource, newData.Operator, newData.IdempotentKey, newData.CreatedTime)
	return err
}

func (m *defaultAeRuleExecutionLogModel) tableName() string {
	return m.table
}
