// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package rules

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	aeRuleFieldNames        = builder.RawFieldNames(&AeRule{}, true)
	aeRuleRows              = strings.Join(aeRuleFieldNames, ",")
	aeRuleRowsExpectAutoSet = strings.Join(
		stringx.Remove(
			aeRuleFieldNames,
			"id",
			"create_at",
			"created_at",
			"update_at",
			"updated_at",
		),
		",",
	)
	aeRuleRowsWithPlaceHolder = builder.PostgreSqlJoin(
		stringx.Remove(
			aeRuleFieldNames,
			"id",
			"create_at",
			"created_at",
			"update_at",
			"updated_at",
		),
	)
)

type (
	aeRuleModel interface {
		Insert(ctx context.Context, data *AeRule) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AeRule, error)
		Update(ctx context.Context, data *AeRule) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAeRuleModel struct {
		conn  sqlx.SqlConn
		table string
	}

	AeRule struct {
		Id           int64          `db:"id"`
		Name         string         `db:"name"`
		Description  sql.NullString `db:"description"`
		Active       string         `db:"active"`
		CronValue    string         `db:"cron_value"`
		FilterConfig string         `db:"filter_config"`
		ActionConfig string         `db:"action_config"`
		CreateTime   time.Time      `db:"create_time"`
		UpdateTime   time.Time      `db:"update_time"`
	}
)

func newAeRuleModel(conn sqlx.SqlConn) *defaultAeRuleModel {
	return &defaultAeRuleModel{
		conn:  conn,
		table: `"public"."ae_cron_rule"`,
	}
}

func (m *defaultAeRuleModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultAeRuleModel) FindOne(ctx context.Context, id int64) (*AeRule, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", aeRuleRows, m.table)
	var resp AeRule
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAeRuleModel) Insert(ctx context.Context, data *AeRule) (sql.Result, error) {
	// 显式指定列名，避免与 aeRuleRowsExpectAutoSet 的字段列表不一致导致占位符索引错误。
	query := fmt.Sprintf(`
		INSERT INTO %s (
			name,
			description,
			active,
			cron_value,
			filter_config,
			action_config,
			create_time,
			update_time
		) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
	`, m.table)
	ret, err := m.conn.ExecCtx(ctx, query,
		data.Name,
		data.Description,
		data.Active,
		data.CronValue,
		data.FilterConfig,
		data.ActionConfig,
		data.CreateTime,
		data.UpdateTime,
	)
	return ret, err
}

func (m *defaultAeRuleModel) Update(ctx context.Context, data *AeRule) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, aeRuleRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query,
		data.Id,
		data.Name,
		data.Description,
		data.Active,
		data.CronValue,
		data.FilterConfig,
		data.ActionConfig,
		data.CreateTime,
		data.UpdateTime,
	)
	return err
}

func (m *defaultAeRuleModel) tableName() string {
	return m.table
}
