// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package rules

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	aeRuleFieldNames          = builder.RawFieldNames(&AeRule{}, true)
	aeRuleRows                = strings.Join(aeRuleFieldNames, ",")
	aeRuleRowsExpectAutoSet   = strings.Join(stringx.Remove(aeRuleFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	aeRuleRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(aeRuleFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	aeRuleModel interface {
		Insert(ctx context.Context, data *AeRule) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AeRule, error)
		Update(ctx context.Context, data *AeRule) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAeRuleModel struct {
		conn  sqlx.SqlConn
		table string
	}

	AeRule struct {
		Id           int64          `db:"id"`
		Name         string         `db:"name"`
		Description  sql.NullString `db:"description"`
		Status       string         `db:"status"`
		Priority     int64          `db:"priority"`
		TriggerKey   string         `db:"trigger_key"`
		FilterConfig string         `db:"filter_config"`
		ActionConfig string         `db:"action_config"`
		CreatedTime  time.Time      `db:"created_time"`
		UpdatedTime  time.Time      `db:"updated_time"`
	}
)

func newAeRuleModel(conn sqlx.SqlConn) *defaultAeRuleModel {
	return &defaultAeRuleModel{
		conn:  conn,
		table: `"public"."ae_rule"`,
	}
}

func (m *defaultAeRuleModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultAeRuleModel) FindOne(ctx context.Context, id int64) (*AeRule, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", aeRuleRows, m.table)
	var resp AeRule
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAeRuleModel) Insert(ctx context.Context, data *AeRule) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8, $9)", m.table, aeRuleRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Name, data.Description, data.Status, data.Priority, data.TriggerKey, data.FilterConfig, data.ActionConfig, data.CreatedTime, data.UpdatedTime)
	return ret, err
}

func (m *defaultAeRuleModel) Update(ctx context.Context, data *AeRule) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, aeRuleRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.Name, data.Description, data.Status, data.Priority, data.TriggerKey, data.FilterConfig, data.ActionConfig, data.CreatedTime, data.UpdatedTime)
	return err
}

func (m *defaultAeRuleModel) tableName() string {
	return m.table
}
