apiVersion: v1
kind: Service
metadata:
  name: {{ include "ae-mgr-be.fullname" . }}
  labels:
    {{- include "ae-mgr-be.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9005
      protocol: TCP
      name: http
  selector:
    {{- include "ae-mgr-be.selectorLabels" . | nindent 4 }}
