// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0-alpha

package config

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	aeMcpExternalServicesAccountFieldNames          = builder.RawFieldNames(&AeMcpExternalServicesAccount{}, true)
	aeMcpExternalServicesAccountRows                = strings.Join(aeMcpExternalServicesAccountFieldNames, ",")
	aeMcpExternalServicesAccountRowsExpectAutoSet   = strings.Join(stringx.Remove(aeMcpExternalServicesAccountFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	aeMcpExternalServicesAccountRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(aeMcpExternalServicesAccountFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	aeMcpExternalServicesAccountModel interface {
		Insert(ctx context.Context, data *AeMcpExternalServicesAccount) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AeMcpExternalServicesAccount, error)
		Update(ctx context.Context, data *AeMcpExternalServicesAccount) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAeMcpExternalServicesAccountModel struct {
		conn  sqlx.SqlConn
		table string
	}

	AeMcpExternalServicesAccount struct {
		Id         int64     `db:"id"`          // 自增id
		Name       string    `db:"name"`        // 账号名称
		AuthInfo   string    `db:"auth_info"`   // 权限信息
		ConfigId   int64     `db:"config_id"`   // 外部服务配置表ID
		CreateTime time.Time `db:"create_time"` // 创建时间
		UpdateTime time.Time `db:"update_time"` // 更新时间
		Status     string    `db:"status"`      // 使用状态：used-使用中，unused-未使用
	}
)

func newAeMcpExternalServicesAccountModel(conn sqlx.SqlConn) *defaultAeMcpExternalServicesAccountModel {
	return &defaultAeMcpExternalServicesAccountModel{
		conn:  conn,
		table: `"public"."ae_mcp_external_services_account"`,
	}
}

func (m *defaultAeMcpExternalServicesAccountModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultAeMcpExternalServicesAccountModel) FindOne(ctx context.Context, id int64) (*AeMcpExternalServicesAccount, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", aeMcpExternalServicesAccountRows, m.table)
	var resp AeMcpExternalServicesAccount
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAeMcpExternalServicesAccountModel) Insert(ctx context.Context, data *AeMcpExternalServicesAccount) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4)", m.table, aeMcpExternalServicesAccountRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Name, data.AuthInfo, data.ConfigId, data.Status)
	return ret, err
}

func (m *defaultAeMcpExternalServicesAccountModel) Update(ctx context.Context, data *AeMcpExternalServicesAccount) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, aeMcpExternalServicesAccountRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.Name, data.AuthInfo, data.ConfigId, data.Status)
	return err
}

func (m *defaultAeMcpExternalServicesAccountModel) tableName() string {
	return m.table
}
