// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package config

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	aeMcpExternalServicesConfigFieldNames          = builder.RawFieldNames(&AeMcpExternalServicesConfig{}, true)
	aeMcpExternalServicesConfigRows                = strings.Join(aeMcpExternalServicesConfigFieldNames, ",")
	aeMcpExternalServicesConfigRowsExpectAutoSet   = strings.Join(stringx.Remove(aeMcpExternalServicesConfigFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	aeMcpExternalServicesConfigRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(aeMcpExternalServicesConfigFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))

	cachePublicAeMcpExternalServicesConfigIdPrefix = "cache:public:aeMcpExternalServicesConfig:id:"
)

type (
	aeMcpExternalServicesConfigModel interface {
		Insert(ctx context.Context, data *AeMcpExternalServicesConfig) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AeMcpExternalServicesConfig, error)
		Update(ctx context.Context, data *AeMcpExternalServicesConfig) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAeMcpExternalServicesConfigModel struct {
		sqlc.CachedConn
		table string
	}

	AeMcpExternalServicesConfig struct {
		Id                int64          `db:"id"`                  // 自增id
		Name              string         `db:"name"`                // 服务名称
		Type              string         `db:"type"`                // 服务类型：stdio-标准输入输出，sse-SSE连接
		LaunchInfo        string         `db:"launch_info"`         // 启动信息，如：{  "command": "node",  "args": ["server.js"],  "workdir": "/opt/mcp/news",  "env": {"PORT": "8080"},  "max_instance":1, //最大实例数  "max_restarts":3, // 实例最大连接数  "launch_timeout":100000, //服务启动超时时间（毫秒）  "shutdown_timeout": 100000,//服务关闭时的超时时间（毫秒）  "idle_ttl": 100000000 //服务空闲存活时间（毫秒）}
		CreateTime        time.Time      `db:"create_time"`         // 创建时间
		UpdateTime        time.Time      `db:"update_time"`         // 更新时间
		ConnectInfo       string         `db:"connect_info"`        // 连接信息，如：{  "url": "http://api.remote.com/mcp/sse",  "headers": {"Authorization": "Bearer xxx"},  "connect_timeout": 3000,//连接超时时间（毫秒）  "max_connect":10,//实例最大连接数  "max_retry":3,//最大重试次数  "interval":1000,//重试间隔}
		ExternalServiceId string         `db:"external_service_id"` // 外部服务唯一标识
		MaxInstance       int64          `db:"max_instance"`        // 最大实例(启动几个服务实例)
		CreateStatus      bool           `db:"create_status"`       // true 已创建 false 未创建
		Description       string         `db:"description"`         // 服务描述
		ProjectName       string         `db:"project_name"`        // 项目名称
		ServerId          string         `db:"server_id"`           // mcp服务ID
		InstallInfo       sql.NullString `db:"install_info"`        // 服务克隆仓库安装命令
		AccountRequired   sql.NullInt64  `db:"account_required"`    // 是否需要账号信息
		TestStatus        sql.NullInt64  `db:"test_status"`         // 1 已测试  0 未测试
		OnlineStatus      sql.NullInt64  `db:"online_status"`       // 1 已上线  0 已下线
	}
)

func newAeMcpExternalServicesConfigModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultAeMcpExternalServicesConfigModel {
	return &defaultAeMcpExternalServicesConfigModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      `"public"."ae_mcp_external_services_config"`,
	}
}

func (m *defaultAeMcpExternalServicesConfigModel) Delete(ctx context.Context, id int64) error {
	publicAeMcpExternalServicesConfigIdKey := fmt.Sprintf("%s%v", cachePublicAeMcpExternalServicesConfigIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where id = $1", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, publicAeMcpExternalServicesConfigIdKey)
	return err
}

func (m *defaultAeMcpExternalServicesConfigModel) FindOne(ctx context.Context, id int64) (*AeMcpExternalServicesConfig, error) {
	publicAeMcpExternalServicesConfigIdKey := fmt.Sprintf("%s%v", cachePublicAeMcpExternalServicesConfigIdPrefix, id)
	var resp AeMcpExternalServicesConfig
	err := m.QueryRowCtx(ctx, &resp, publicAeMcpExternalServicesConfigIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where id = $1 limit 1", aeMcpExternalServicesConfigRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAeMcpExternalServicesConfigModel) Insert(ctx context.Context, data *AeMcpExternalServicesConfig) (sql.Result, error) {
	publicAeMcpExternalServicesConfigIdKey := fmt.Sprintf("%s%v", cachePublicAeMcpExternalServicesConfigIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)", m.table, aeMcpExternalServicesConfigRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Name, data.Type, data.LaunchInfo, data.ConnectInfo, data.ExternalServiceId, data.MaxInstance, data.CreateStatus, data.Description, data.ProjectName, data.ServerId, data.InstallInfo, data.AccountRequired, data.TestStatus, data.OnlineStatus)
	}, publicAeMcpExternalServicesConfigIdKey)
	return ret, err
}

func (m *defaultAeMcpExternalServicesConfigModel) Update(ctx context.Context, data *AeMcpExternalServicesConfig) error {
	publicAeMcpExternalServicesConfigIdKey := fmt.Sprintf("%s%v", cachePublicAeMcpExternalServicesConfigIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where id = $1", m.table, aeMcpExternalServicesConfigRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Id, data.Name, data.Type, data.LaunchInfo, data.ConnectInfo, data.ExternalServiceId, data.MaxInstance, data.CreateStatus, data.Description, data.ProjectName, data.ServerId, data.InstallInfo, data.AccountRequired, data.TestStatus, data.OnlineStatus)
	}, publicAeMcpExternalServicesConfigIdKey)
	return err
}

func (m *defaultAeMcpExternalServicesConfigModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cachePublicAeMcpExternalServicesConfigIdPrefix, primary)
}

func (m *defaultAeMcpExternalServicesConfigModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", aeMcpExternalServicesConfigRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultAeMcpExternalServicesConfigModel) tableName() string {
	return m.table
}
